### ISSUE TITLE
Can't download pkl files

### ISSUE THREAD

**Issue by kentkawai** [tapilab/aaai-2015-demographics#3]
Hi,

I can't download all .pkl files. All urls to .pkl files return the error 'connection refused'.
Where can I download them?

**Comment by aronwc** [comment]
[sent email to kent]

**Comment by saranshgupta12** [comment]
Hi Aron,

I am trying to reproduce the exact results from your paper for academic purposes. Could you kindly share the original .pkl files? The links provided seem to be broken. Thanks!

**Comment by aronwc** [comment]
@saranshgupta12 Send me an email: aronwc at gmail
